[package]
name = "rust-chat"
version = "0.1.2"
edition = "2021"
description = "A Chat app over TCP Sockets"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.23.0"
chrono = "0.4"
notify-rust = "4.5.6"